gysinge/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import (
handler400, handler403, handler404, handler500
)
handler400 = 'maltlager.views.bad_request'
handler403 = 'maltlager.views.access_denied'
handler404 = 'maltlager.views.page_not_found'
handler500 = 'maltlager.views.server_error'

urlpatterns = [
    url(r'^', include('maltlager.urls')),
]

maltlager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^activities/$', views.activities, name='activities'),
    url(r'^edit_activity/(?P<activity_id>.+)/$', views.edit_activity, name='edit_activity'),
    url(r'^delete_activity/(?P<activity_id>.+)/$', views.delete_activity, name='delete_activity'),
    url(r'^members/$', views.members, name='members'),
    url(r'^edit_board_member/(?P<board_member_id>.+)/$', views.edit_board_member, name='edit_board_member'),
    url(r'^delete_board_member/(?P<board_member_id>.+)/$', views.delete_board_member, name='delete_board_member'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^malts/$', views.list_malts, name='list_malts'),
    url(r'^access_denied/$', views.access_denied, name='access_denied'),
    url(r'^invalid_user/$', views.invalid_user, name='invalid_user'),
    url(r'^invalid_form/$', views.invalid_form, name='invalid_form'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^create_user/$', views.create_user, name='create_user'),
    url(r'^delete_user/(?P<username>.+)/$', views.delete_user, name='delete_user'),
    url(r'^grant_staff/(?P<username>.+)/$', views.grant_staff, name='grant_staff'),
    url(r'^revoke_staff/(?P<username>.+)/$', views.revoke_staff, name='revoke_staff'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^hops/$', views.list_hops, name='list_hops'),
    url(r'^malt_form/$', views.malt_form, name='malt_form'),
    url(r'^hops_form/$', views.hops_form, name='hops_form'),
    url(r'^history/malt/$', views.history_malt, name='history_malt'),
    url(r'^history/hops/$', views.history_hops, name='history_hops'),
    url(r'^malt_history/(?P<current_malt>.+)/$', views.malt_history, name='malt_history'),
    url(r'^hops_history/(?P<current_hops>.+)/$', views.hops_history, name='hops_history'),
    url(r'^malt/(?P<current_malt>.+)/$', views.update_malt_form, name='update_malt_form'),
    url(r'^hops/(?P<current_hops>.+)/$', views.update_hops_form, name='update_hops_form'),
]

maltlager/models.py
from django.db import models

class malt(models.Model):
    name = models.CharField(max_length=100)
    amount = models.FloatField(default=0)

class hops(models.Model):
    name = models.CharField(max_length=100)
    amount = models.FloatField(default=0)

class maltchange(models.Model):
    name = models.CharField(max_length=100)
    amount = models.FloatField(default=0)
    time = models.DateTimeField()
    user = models.CharField(max_length=100,default="unknown")

class hopschange(models.Model):
    name = models.CharField(max_length=100)
    amount = models.FloatField(default=0)
    time = models.DateTimeField()
    user = models.CharField(max_length=100,default="unknown")

class board_member(models.Model):
    name = models.CharField(max_length=200)
    role = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/board_member')

class activity(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateTimeField(help_text='Format: YYYY-MM-DD HH:MM')
    content = models.TextField()

maltlager/forms.py
from django import forms

class MaltForm(forms.Form):
    name = forms.CharField(max_length=20)
    amount = forms.FloatField()

class HopsForm(forms.Form):
    name = forms.CharField(max_length=20)
    amount = forms.FloatField()

class UpdateMaltForm(forms.Form):
    amount = forms.FloatField()

class UpdateHopsForm(forms.Form):
    amount = forms.FloatField()

class CreateUserForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput())

class BoardMemberForm(forms.Form):
    name = forms.CharField(max_length=200)
    role = forms.CharField(max_length=200)
    description = forms.CharField(max_length=200)
    image = forms.ImageField()

class ActivityForm(forms.Form):
    title = forms.CharField(max_length=200)
    date = forms.DateTimeField()
    content = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.Form):
    name = forms.CharField(max_length=200)
    mail = forms.CharField(max_length=200)
    content = forms.CharField(max_length=10000)

maltlager/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, views
from django.core.mail import send_mail
from maltlager.models import malt, hops, maltchange, hopschange, board_member, activity
from maltlager.forms import MaltForm, UpdateMaltForm, HopsForm, UpdateHopsForm, CreateUserForm, BoardMemberForm, ActivityForm, ContactForm
from django.utils import timezone
import django.db
import os

def bad_request(request):
    context = {'active_page': 'bad_request'}
    return render(request, 'maltlager/400.html', {})

def page_not_found(request):
    context = {'active_page': 'page_not_found'}
    return render(request, 'maltlager/404.html', {})

def server_error(request):
    context = {'active_page': 'server_error'}
    return render(request, 'maltlager/500.html', {})

def access_denied(request):
    context = {'active_page': 'access_denied'}
    return render(request, 'maltlager/access_denied.html', context)

def invalid_form(request):
    context = {'active_page': 'invalid_form'}
    return render(request, 'maltlager/invalid_form.html', context)

def index(request):
    context = {'active_page': 'home'}
    return render(request, 'maltlager/index.html', context)

def about(request):
    context = {'active_page': 'about'}
    return render(request, 'maltlager/about.html', context)

def activities(request):
    activity_list = activity.objects.all().order_by('-date')
    context = {'active_page': 'activities', 'activity_list': activity_list}
    return render(request, 'maltlager/activities.html', context)

def edit_activity(request, activity_id):
    if request.user.is_staff:
        if request.method == 'POST':
            form = ActivityForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                form_title = data.get('title')
                form_date = data.get('date')
                form_content = data.get('content')
                try:
                    a = activity.objects.get(id=activity_id)
                    if a:
                        a.title = form_title
                        a.date = form_date
                        a.content = form_content
                        a.save()
                except:
                    a = activity(title=form_title,date=form_date,content=form_content)
                    a.save()
                return HttpResponseRedirect('/activities/')
            else:
                return HttpResponseRedirect('/invalid_form/')
        else:
            try:
                a = activity.objects.get(id=activity_id)
                if a:
                    data = {'title': a.title, 'date': a.date, 'content': a.content}
                    form = ActivityForm(initial=data)
                else:
                    form = ActivityForm()
            except:
                form = ActivityForm()
            context = {'form': form, 'active_page': 'activities', 'activity_id': activity_id}
            return render(request, 'maltlager/edit_activity.html', context)
    else:
        return HttpResponseRedirect('/access_denied/')

def delete_activity(request, activity_id):
    if request.user.is_staff:
        try:
            a = activity.objects.get(id=activity_id)
            a.delete()
            return HttpResponseRedirect('/activities/')
        except:
            return HttpResponseRedirect('/activities/')
    else:
        return HttpResponseRedirect('/access_denied/')

def members(request):
    bm = board_member.objects.all().order_by('name')
    context = {'active_page': 'members', 'board_member_list': bm}
    return render(request, 'maltlager/members.html', context)

def edit_board_member(request, board_member_id):
    if request.user.is_staff:
        if request.method == 'POST':
            if not board_member_id == 'new':
                form = BoardMemberForm(request.POST, request.FILES)
                bm = board_member.objects.get(id=board_member_id)
                if bm:
                    if form.is_valid():
                        data = form.cleaned_data
                        form_image = request.FILES['image']
                        form_name = data.get('name')
                        form_role = data.get('role')
                        form_description = data.get('description')
                    else:
                        data = request.POST
                        if request.FILES.get('image'):
                            form_image = request.FILES.get('image')
                        else:
                            form_image = None
                        if data.get('name'):
                            form_name = data.get('name')
                        else:
                            form_name = None
                        if data.get('role'):
                            form_role = data.get('role')
                        else:
                            form_role = None
                        if data.get('description'):
                            form_description = data.get('description')
                        else:
                            form_description = None
                    if form_name:
                        bm.name = form_name
                    if form_role:
                        bm.role = form_role
                    if form_description:
                        bm.description = form_description
                    if form_image:
                        bm.image = form_image
                    bm.save()
                else:
                    if form.is_valid():
                        data = form.cleaned_data
                        form_image = request.FILES['image']
                        form_name = data.get('name')
                        form_role = data.get('role')
                        form_description = data.get('description')
                        bm = board_member(name=form_name,role=form_role,description=form_description,image=form_image)
                        bm.save()
                    else:
                        return HttpResponseRedirect('/invalid_form/')
                return HttpResponseRedirect('/members/')
            else:
                form = BoardMemberForm(request.POST, request.FILES)
                if form.is_valid():
                    data = form.cleaned_data
                    form_image = request.FILES['image']
                    form_name = data.get('name')
                    form_role = data.get('role')
                    form_description = data.get('description')
                else:
                    return HttpResponseRedirect('/invalid_form/')
                bm = board_member(name=form_name,role=form_role,description=form_description,image=form_image)
                bm.save()
            return HttpResponseRedirect('/members/')
        else:
            try:
                bm = board_member.objects.get(id=board_member_id)
                if bm:
                    data = {'name': bm.name, 'role': bm.role, 'description': bm.description, 'image': bm.image}
                    form = BoardMemberForm(initial=data)
                else:
                    form = BoardMemberForm()
            except:
                form = BoardMemberForm()
            context = {'form': form, 'active_page': 'members', 'board_member_name': board_member_id}
            return render(request, 'maltlager/board_member.html', context)
    else:
        return HttpResponseRedirect('/access_denied/')

def delete_board_member(request, board_member_id):
    if request.user.is_staff:
        try:
            bm = board_member.objects.get(id=board_member_id)
            bm.delete()
            return HttpResponseRedirect('/members/')
        except:
            return HttpResponseRedirect('/members/')
    else:
        return HttpResponseRedirect('/access_denied/')

def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        mail = request.POST['mail']
        content = request.POST['content']
        if name is not None and mail is not None and content is not None:
            send_mail(
                'Gysinge Bryggerisällskap, message from: ' + name,
                'The following message was received by ' + name + ' (' + mail + ')\n\n' + content,
                'info@gysingebryggeri.se',
                ['info@gysingebryggeri.se'],
                fail_silently=False,
            )
            return HttpResponseRedirect('/contact/#valid')
        else:
            return HttpResponseRedirect('/contact/#invalid')
    else:
        form = ContactForm()
        context = {'form': form, 'active_page': 'contact'}
        return render(request, 'maltlager/contact.html', context)

def calendar(request):
    context = {'active_page': 'calendar'}
    return render(request, 'maltlager/calendar.html', context)

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect('/inactive_user/')
        else:
            return HttpResponseRedirect('/invalid_user/')
    else:
        form = AuthenticationForm(request)
        context = {'form': form, 'active_page': 'login'}
        return render(request, 'maltlager/login.html', context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def create_user(request):
    if request.user.is_staff:
        if request.method == 'POST':
            form = CreateUserForm(request.POST)

maltlager/templates/maltlager/access_denied.html
{% extends 'maltlager/base.html' %}
{% block block_title %}{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <p style="text-align: center">
                You tried to access a page that you don't have access to!
            </p>
        </div>
    </div>
{% endblock %}

maltlager/templates/maltlager/activities.html
{% extends 'maltlager/base.html' %}
{% load markdown_deux_tags %}
{% block block_title %}{% endblock %}
{% block content %}
    <div class="container">
        <img class="banner-image" src="/static/resources/images/hops-banner.png" alt="Banner image">
    </div>
    <h1 class="centered">Aktiviteter</h1>
    <div class="jumbotron">
        <div class="container">
            {% if activity_list %}
                {% for activity in activity_list %}
                    <div class="jumbotron">
                        <div class="article">
                            <div class="page-header">
                                <h2>{{ activity.title }}</h2>
                            </div>
                            <div class="row">
                                <p>{{ activity.date|date:'Y-m-d H:i' }}</p>
                            </div>
                            <div class="row">
                                {{ activity.content|markdown }}
                            </div>
                            {% if request.user.is_staff %}
                                <div class="row">
                                    <a class="btn btn-primary" style="display: block; width: 120px; float: left;" href="/edit_activity/{{ activity.id }}/">Edit</a>
                                    <a class="btn btn-danger" style="display: block; width: 120px; float: right;" href="/delete_activity/{{ activity.id }}/">Delete</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                        <p style="text-align: center">Här kommer vi att lägga upp information om de aktiviteter som är på gång i bryggeriet.</p>
            {% endif %}
            {% if request.user.is_staff %}
                <a class="btn btn-primary" style="display: block; width: 120px; margin: auto;" href="/edit_activity/new/">Add Activity</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

maltlager/templates/maltlager/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="/static/resources/images/logga.png">
        <title>Gysinge Bryggerisällskap</title>
        <link rel="stylesheet" href="/static/css/bootstrap.css">
    </head>
    <body>
        <!--<div class="container alert alert-info" style="text-align: center;" role="alert"><strong>Information:</strong> Den här sidan är under utveckling, och allt funkar inte som det är tänk än. Tack för överseendet!</div>-->
        <div class="container">
            <div class="navbar navbar-default">
                <div class="navbar-header col-lg-3 col-md-12 col-sm-12">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a href="/" style="width: 150px; display: block; margin: auto;">
                        <img src="/static/resources/images/logga.png" alt="Gysinge Bryggerisällskap logga" style="width: 150px; height: 100px;">
                    </a>
                </div>
                <div class="collapse navbar-right navbar-collapse col-lg-9" id="bs-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        {% if active_page = "home" %}
                            <li class="active"><a href="/">Hem<span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="/">Hem</a></li>
                        {% endif%}
                        {% if active_page = "about" %}
                            <li class="active"><a href="/about/">Om oss<span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="/about/">Om oss</a></li>
                        {% endif%}
                        {% if active_page = "activities" %}
                            <li class="active"><a href="/activities/">Aktiviteter<span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="/activities/">Aktiviteter</a></li>
                        {% endif%}
                        {% if active_page = "members" %}
                            <li class="active"><a href="/members/">Medlemmar<span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="/members/">Medlemmar</a></li>
                        {% endif%}
                        {% if active_page = "contact" %}
                            <li class="active"><a href="/contact/">Kontakta oss<span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="/contact/">Kontakta oss</a></li>
                        {% endif%}
                        {% if active_page = "calendar" %}
                            <li class="active"><a href="/calendar/">Kalender<span class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li><a href="/calendar/">Kalender</a></li>
                        {% endif%}
                        {% if request.user.is_authenticated %} 
                            {% if active_page = "maltlager" %}
                                <li class="active"><a href="/malts/">Maltlager<span class="sr-only">(current)</span></a></li>
                            {% else %}
                                <li><a href="/malts/">Maltlager</a></li>
                            {% endif%}
                            {% if request.user.is_staff %} 
                                {% if active_page = "settings" %}
                                    <li class="active"><a href="/settings/">Inställningar</a></li>
                                {% else %}
                                    <li><a href="/settings/">Inställningar</a></li>
                                {% endif%}
                            {% endif %}
                            <li><a href="/logout/">Logga ut ({{request.user.username}})</a></li>
                        {% else %}
                            {% if active_page = "login" %}
                                <li class="active"><a href="/login/">Logga in</a></li>
                            {% else %}
                                <li><a href="/login/">Logga in</a></li>
                            {% endif%}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            {% block block_title %}
            <div class="page-header">
                <h1 style="text-align:center">Maltlager</h1>
            </div>
            {% endblock %}
            {% block content %}
                
            {% endblock %}
        </div>
        <div class="container footer">
            <div class="footer-padding">
                <div class="visible-lg col-md-3">
                    <a href="https://www.facebook.com/Gysinge-Bryggeris%C3%A4llskap-Norrlands-sydligaste-bryggeri-614297191957410/">
                        <img class="img-circle" style="height: 50px; width: 50px;" alt="Facebook logo" src="/static/resources/images/facebook.png">
                    </a>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 footer-text">
                    <h4 style="text-align: center;">Gysinge Bryggerisällskap</h4>
                </div>
                <div class="visible-lg col-md-3 footer-text">
                    <h4 style="text-align: right;"> info@gysingebryggeri.se</h4>
                </div>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    </body>
</html>

maltlager/templates/maltlager/contact.html
{% extends 'maltlager/base.html' %}
{% block block_title %}{% endblock %}
{% block content %}
    <div class="container">
        <img class="banner-image" src="/static/resources/images/hops-banner.png" alt="Banner image">
    </div>
    <div class="jumbotron">
        <div class="container">
            <div id="valid" class="alert alert-success" style="display: none;">
                <strong>Tack!</strong> Ditt meddelande har skickats!
            </div>
            <div id="invalid" class="alert alert-danger" style="display: none;">
                <strong>Fel!</strong> Ditt meddelande kunde inte skickas. Har du fyllt i alla fält?
            </div>
            <br>
            <form action="" method="post" class="form-vertical">
                <div class="container" style="width: 80%; display: block; margin: auto; height: auto;" >
                    {% csrf_token %}
                    <label class="col-md-2 col-xs-2" style="text-align: right;" for="id_name">Namn: </label>
                    <input class="col-md-10 col-xs-10" id="id_name" maxlength="200" name="name" type="text" required>
                    <br>
                    <br>
                    <label class="col-md-2 col-xs-2" style="text-align: right;" for="id_mail">Mail: </label>
                    <input class="col-md-10 col-xs-10" id="id_mail" maxlength="200" name="mail" type="email" required>
                    <br>
                    <br>
                    <label class="col-md-2 col-xs-2" style="text-align: right;" for="id_content">Meddelande: </label>
                    <input class="col-md-10 col-xs-10" id="id_content" maxlength="10000" name="content" type="text" required>
                </div>
                <br>
                <input type="submit" style="width: 100px; display: block; margin: auto;" class="btn btn-primary" value="Skicka" />
            </form>
        </div>
    </div>
    <script type="text/javascript">
    if (location.href.indexOf("#valid") != -1) {
        document.getElementById("valid").style.display = "block";
    }
    if (location.href.indexOf("#invalid") != -1) {
        document.getElementById("invalid").style.display = "block";
    }
    </script>
{% endblock %}

maltlager/templates/maltlager/create_user.html
{% extends 'maltlager/base.html' %}
{% block block_title %}
    <div class="page-header">
        <h1 style="text-align:center">Creating user</h1>
    </div>
{% endblock %}
{% block content %}
    <div class="jumbotron">        
        <div class="container">        
            <form action="" method="post" class="form-vertical">
                <div style="max-width: 180px; width: 180px; margin: 0 auto;" >
                    {% csrf_token %}
                    {{ form }}
                </div>
                <div style="width: 100px; margin: 0 auto;" >
                    <br>
                    <input type="submit" style="width: 100px" class="btn btn-primary" value="Create User" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

maltlager/templates/maltlager/history_hops.html
{% extends 'maltlager/base.html' %}
{% block block_title %}
    <div class="page-header">
        <h1 style="text-align:center">History for hops</h1>
    </div>
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li><a href="/malts/">Malt</a></li>
                    <li class="active"><a href="/hops/">Hops</a></li>
                </ul>
                <div class="tab-content">
                    <div class="container">
                        {% if hops_change_list %}
                            <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Amount</th>
                                    <th>Time</th>
                                    <th>User</th>
                                </tr>
                            </thead>
                            {% for hops_change in hops_change_list %}
                                <tr>
                                    <td style="vertical-align:middle" class="col-md-3">{{ hops_change.name }}</td>
                                    <td style="vertical-align:middle" class="col-md-3">{{ hops_change.amount }} kg</td>
                                    <td style="vertical-align:middle" class="col-md-3">{{ hops_change.time|date:'Y-m-d H:i' }}</td>
                                    <td style="vertical-align:middle" class="col-md-3">{{ hops_change.user }}</td>
                                </tr>
                            {% endfor %}
                            </table>
                        {% else %}
                            <p>No history available for hops!</p>
                        {% endif %}
                        <a style="float:left; margin-bottom:15px" class="btn btn-primary" href="/hops/">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

maltlager/templates/maltlager/history_malt.html
{% extends 'maltlager/base.html' %}
{% block block_title %}
    <div class="page-header">
        <h1 style="text-align:center">History for malt</h1>
    </div>
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <div class="tabbable">
                <ul class="nav nav-tabs">
                <li class="active"><a href="/malts/">Malt</a></li>
                <li><a href="/hops/">Hops</a></li>
                </ul>
                <div class="tab-content">
                {% if malt_change_list %}
                    <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Time</th>
                        <th>User</th>
                    </tr>
                    </thead>
                    {% for malt_change in malt_change_list %}
                    <tr>
                        <td style="vertical-align:middle" class="col-md-3">{{ malt_change.name }}</td>
                        <td style="vertical-align:middle" class="col-md-3">{{ malt_change.amount }} kg</td>
                        <td style="vertical-align:middle" class="col-md-3">{{ malt_change.time|date:'Y-m-d H:i' }}</td>
                        <td style="vertical-align:middle" class="col-md-3">{{ malt_change.user }}</td>
                    </tr>
                    {% endfor %}
                    </table>
                {% else %}
                    <p>No history available for malt!</p>
                {% endif %}
                <a style="float:left; margin-bottom:15px" class="btn btn-primary" href="/malts/">Back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

maltlager/templates/maltlager/invalid_form.html
{% extends 'maltlager/base.html' %}
{% block block_title %}{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <p style="text-align: center">
                You tried to submit a form with invalid data! (Did you fill in all fields?)
            </p>
        </div>
    </div>
{% endblock %}

maltlager/templates/maltlager/login.html
{% extends 'maltlager/base.html' %}
{% block block_title %}{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="container">        
            <form action="" method="post" class="form-vertical">
                <div style="max-width: 180px; width: 180px; margin: 0 auto;" >
                    {% csrf_token %}
                    {{ form }}
                </div>
                <div style="width: 100px; margin: 0 auto;" >
                    <br>
                    <input type="submit" style="width: 100px" class="btn btn-primary" value="Login" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}